- name: Install dotter
  kewlfft.aur.aur:
    state: latest
    name: dotter-rs-bin

- name: Clone dotfiles
  git:
    repo: https://github.com/serkonda7/dotfiles
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    update: true

- name: Create local.toml
  copy:
    dest: "{{ ansible_env.HOME }}/.dotfiles/.dotter/local.toml"
    content: |
      includes = [".dotter/default.toml"]
      packages = ["default"]
    
- name: Deploy dotfiles
  command: dotter deploy --force
  args:
    chdir: "{{ ansible_env.HOME }}/.dotfiles"