- name: Install VS Code
  community.general.pacman:
    state: latest
    name: code

- name: Install code-marketplace
  kewlfft.aur.aur:
    state: latest
    name: code-marketplace

- name: Install extensions
  command: "code --install-extension {{ item }}"
  with_items:
    - bierner.markdown-footnotes
    - bierner.markdown-mermaid
    - eamodio.gitlens
    - editorconfig.editorconfig
    - redhat.vscode-yaml
    - tamasfe.even-better-toml
    - vscode-icons-team.vscode-icons
    - yzhang.markdown-all-in-one
