- name: Remove packages
  become: true
  community.general.pacman:
    state: absent
    name: "{{ item }}"
  with_items:
    - eos-apps-info
    - eos-quickstart
    - firefox
    - firewalld
    - glances
    - haruna
    - kdeconnect
    - mpvqt
    - meld
    - okular
    - plasma-firewall
    - print-manager
    - welcome
  register: removals
  changed_when: removals.changed

- name: Install packages
  become: true
  community.general.pacman:
    state: latest
    name: "{{ item }}"
  with_items:
    - falkon
    - fastfetch

- name: Cleanup orphan dependencies
  ansible.builtin.command: yay -Yc --noconfirm
  register: cleanup
  changed_when: cleanup.stdout != ""

- name: Upgrade all packages
  become: true
  community.general.pacman:
    upgrade: true
  register: upgrades
  changed_when: upgrades.changed

- name: Recommend system reboot
  when: removals.changed or upgrades.changed
  ansible.builtin.debug:
    msg: "Reboot recommended!"
