- name: Remove packages
  become: true
  community.general.pacman:
    state: absent
    name: "{{ item }}"
  with_items:
    - eos-apps-info
    - eos-quickstart
    - firefox
    - firewalld
    - haruna
    - kdeconnect
    - mpvqt
    - meld
    - okular
    - welcome

- name: Install packages
  become: true
  community.general.pacman:
    state: latest
    name: "{{ item }}"
  with_items:
    - falkon
    - fastfetch

- name: Cleanup orphan dependencies
  command: yay -Yc --noconfirm
