- name: Provision EndeavourOS Virtual Machines
  hosts: localhost
  roles:
    - role: lts-kernel
      tags: [lts-kernel]
    - role: packages
      tags: [packages]
    - role: vscode
      tags: [vscode]
    - role: dotfiles
      tags: [dotfiles]
